### PR TITLE
Hotfix Accordion to work with one AccordionPanel child.

### LINKED ISSUE #2340: Accordion breaks with only one child AccordionPanel.
If an `Accordion` component only has one child `AccordionPanel` (instead of an array of children), an error is thrown:

```js
<Accordion id="base-example-accordion">
  <AccordionPanel
    expanded={this.state.expandedPanels[item.id]}
    id={item.id}
    key={item.id}
    onTogglePanel={(event) => this.togglePanel(event, item)}
    summary={item.summary}
  >
    {item.details}
  </AccordionPanel>
</Accordion>
</Accordion>
```

```
TypeError: this.props.children.map is not a function
```

This is caused by the use of `this.props.children.map` instead of `React.Children.map(this.props.children, ...)`, and was introduced in https://github.com/salesforce/design-system-react/commit/85d5f95d96916406a4412282591e966e7f06bc44#diff-9aa83a65fc3e3eca94fef33122dba6efR68

PR fix coming shortly.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
Fixes #2340.

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
Please `lint:fix` and I will merge

**Comment by jgerigmeyer** [comment]
@interactivellama Fixed!

**Comment by interactivellama** [comment]
Great bug find. We appreciate it!
