### ISSUE TITLE
Accordion breaks with only one child AccordionPanel.

### ISSUE THREAD

**Issue by jgerigmeyer** [salesforce/design-system-react#2340]
If an `Accordion` component only has one child `AccordionPanel` (instead of an array of children), an error is thrown:

```js
<Accordion id="base-example-accordion">
  <AccordionPanel
    expanded={this.state.expandedPanels[item.id]}
    id={item.id}
    key={item.id}
    onTogglePanel={(event) => this.togglePanel(event, item)}
    summary={item.summary}
  >
    {item.details}
  </AccordionPanel>
</Accordion>
</Accordion>
```

```
TypeError: this.props.children.map is not a function
```

This is caused by the use of `this.props.children.map` instead of `React.Children.map(this.props.children, ...)`, and was introduced in https://github.com/salesforce/design-system-react/commit/85d5f95d96916406a4412282591e966e7f06bc44#diff-9aa83a65fc3e3eca94fef33122dba6efR68

PR fix coming shortly.
